"""A few mappings we use while processing Wood.txt"""

shakespeare_aliases = [
    "Ham",
    "Mer. of Ven",
    "Mer. of Venice",
    "As You Like It",
    "Othello",
    "Rom. and Jul",
    "Much Ado",
    "Love",
    "Macb",
    "Meas. for Meas",
    "King Lear",
    "Mid. N. Dream",
    "Mid. N",
    "Mid. Night",
    "Merry Wives",
    "Rich. II",
    "Tam. of Shrew",
    "Com. of Errors",
    "Tam. the Shrew",
]


auth_lang_map = {
    "Goethe": "German",
    "Carlyle": "Scottish",
    "Emerson": "American",
    "Hor": "Latin",
    "Ruskin": "English",
    "Schiller": "German",
    "Bible": "Religion",
    "Johnson": "English",
    "Cic": "Latin",
    "Ovid": "Latin",
    "Virg": "Latin",
    "Jean Paul": "German",
    "Goldsmith": "Irish",
    "Law": "Law",
    "Burns": "Scottish",
    "Sen": "Latin",
    "Pope": "English",
    "Tennyson": "English",
    "Bacon": "English",
    "Thomas à Kempis": "German",
    "Hitopadesa": "Sanskrit",
    "La Roche": "French",
    "Juv": "Latin",
    "Schopenhauer": "German",
    "Byron": "English",
    "Colton": "American",
    "Milton": "English",
    "George Herbert": "English",
    "Ward Beecher": "American",
    "Amiel": "Swiss",
    "La Bruyère": "French",
    "Jesus": "Religion",
    "George Eliot": "English",
    "Dryden": "English",
    "Plaut": "Latin",
    "Young": "English",
    "Wordsworth": "English",
    "Lowell": "American",
    "Swift": "Irish",
    "Ter": "Latin",
    "Disraeli": "English",
    "Pascal": "French",
    "Thoreau": "American",
    "Pub. Syr": "American",
    "Cowper": "English",
    "Voltaire": "French",
    "Rousseau": "Swiss",
    "Joubert": "French",
    "Bovee": "American",
    "Longfellow": "American",
    "St. Paul": "Religion",
    "Quarles": "English",
    "Coleridge": "English",
    "Burke": "English",
    "Tac": "Latin",
    "Scott": "Scottish",
    "Jul. Cæs": "Latin",
    "Cæs": "Latin",
    "Sterne": "English",
    "Rückert": "German",
    "Montaigne": "French",
    "Lessing": "German",
    "Bulwer Lytton": "English",
    "Napoleon": "French",
    "Hen. VI": "English",
    "Addison": "English",
    "Hazlitt": "English",
    "Fuller": "American",
    "Holmes": "American",
    "Hare": "English",
    "Hen. IV": "English",
    "Cervantes": "Spanish",
    "Lavater": "Swiss",
    "Spurgeon": "English",
    "Plato": "Greek",
    "La Font.": "French",
    "La Fontaine": "French",
    "J. G. Holland": "American",
    "Landor": "English",
    "Keble": "English",
    "Sir P. Sidney": "English",
    "Luther": "German",
    "A. B. Alcott": "American",
    "Vauvenargues": "French",
    "Chamfort": "French",
    "Bodenstedt": "German",
    "Browning": "English",
    "Ben. Franklin": "American",
    "Lewis Morris": "American",
    "Novalis": "German",
    "Shakespeare": "English",
    "Montesquieu": "French",
    "Mart": "Latin",
    "Renan": "French",
    "Rich. II": "English",
    "Heine": "German",
    "Locke": "English",
    "Love": "English",
    "J. M. Barrie": "Scottish",
    "Dickens": "English",
    "Froude": "English",
    "Thomson": "Scottish",
    "Lucan": "Latin",
    "Butler": "English",
    "Macaulay": "English",
    "King John": "English",
    "Saadi": "Persian",
    "Chapin": "American",
    "J. S. Mill": "English",
    "Thackeray": "English",
    "Molière": "French",
    "Platen": "German",
    "Rich. III": "English",
    "Mme. Swetchine": "Russian",
    "Fielding": "English",
    "King Lear": "English",
    "Victor Hugo": "French",
    "Arist": "Greek",
    "Ben Jonson": "English",
    "Boileau": "French",
    "Corneille": "French",
    "Chesterfield": "English",
    "Wm. Blake": "English",
    "Junius": "English",
    "Hume": "English",
    "Epictetus": "Greek",
    "Confucius": "Chinese",
    "Law": "Latin",
}

auth_abbrev_map = {
    "Apul": "Apuleius",
    "Arist": "Aristotle",
    "Aul. Gell": "Aulus Gellius",
    "Cæs": "Cæsar",
    "Catull": "Catullus",
    "Cic": "Cicero",
    "Claud": "Claudius, Claudian",
    "Corn": "Corneille",
    "Curt": "Curtius",
    "Eurip": "Euripides",
    "Hom": "Homer",
    "Hor": "Horace",
    "Jul": "Julius",
    "Just": "Justinian",
    "Juv": "Juvenal",
    "Laber": "Labertius",
    "L": "Law",
    "La Font": "La Fontaine",
    "La Roche": "La Rochefoucauld",
    "Liv": "Livy",
    "Luc": "Lucan",
    "Lucr, Lucret": "Lucretius",
    "Macrob": "Macrobius",
    "Mart": "Martial",
    "Mol": "Molière",
    "Per": "Persius",
    "Petron": "Petronius",
    "Phæd, Phædr": "Phædrus",
    "Plaut": "Plautus",
    "Pub. Syr": "Publius Syrus",
    "Quinct": "Quinctilian",
    "Sall": "Sallust",
    "Schill": "Schiller",
    "Sen": "Seneca",
    "Sh": "Shakespeare",
    "Soph": "Sophocles",
    "Stat": "Statius",
    "St. Aug": "St. Augustine",
    "Sueton": "Suetonius",
    "Tac": "Tacitus",
    "Ter": "Terence",
    "Tert": "Tertullian",
    "Tibull": "Tibullus",
    "Virg": "Virgil",
}

origin_abbrev_map = {
    "Bret": "Breton",
    "Dan": "Danish",
    "Dut": "Dutch",
    "Eng": "English",
    "Fr": "French",
    "Fris": "Frisian",
    "Gael": "Gaelic",
    "Ger": "German",
    "Gr": "Greek",
    "Heb": "Hebrew",
    "It": "Italian",
    "Japan": "Japanese",
    "Lat": "Latin",
    "Port": "Portuguese",
    "Russ": "Russian",
    "Sc": "Scottish",
    "Sp": "Spanish",
    "Swed": "Swedish",
    "Turk": "Turkish",
    "Amer": "American",
    "Arab": "Arabic",
    "American-Indian": "American-Indian",
    "Old Ger": "German",
    "Old Fr": "French",
    "Ven": "Venitian",
    "Chinese": "Chinese",
    "Irish": "Irish",
    "English": "English",
    "Spanish": "Spanish",
    "Icelandic": "Icelandic",
    "Iceland": "Icelandic",
    "Lapland": "Lapland",
    "Greek": "Greek",
    "Persian": "Persian",
    "Hindu": "Hindu",
}
